WIP: improve goxygen for model settings
pik-piam/goxygen pull request #21
Opened 2023-08-11 07:56 UTC by whitehacker

This pull request introduces improvements to goxygen, allowing developers to organize better and separate model settings from other parts of the documentation. The core of this enhancement extracts setting blocks from the `main.gms` file and uses them to generate distinct web pages.

Setting blocks intended for extraction should be marked with the tag: `@code extrapage="ExtraPageName"`. This tag serves as an identifier and also provides the name for the generated webpage. 

The feature is still under development and I would appreciate any feedback, comments, or contributions to further refine and improve this implementation. If there are specific use cases or scenarios that should be considered, please let me know.

2023-08-31 07:46 UTC, tscheypidi requested changes
The implementation needs some adjustments in order to work properly. In addition, it would be also important to add tests which verify that the implementation is working as intended. Perhaps you should write these tests first before you focus on fixing the problems in the implementation

2023-08-31 07:46 UTC, tscheypidi commented on R/extractDocumentation.R
> +    if (grepl("@code extrapage", x[1])) {
please don't overwrite previous functionality but rather integrate it. Here, you overwrite the type argument and only catch a very specific case. the extrapage-Feature should work for any type, in particular it should also work for @equation

2023-08-31 07:46 UTC, tscheypidi commented on R/extractDocumentation.R
> +    # if (!is.null(extraPage)) {
please remove commented code

2023-08-31 07:46 UTC, tscheypidi commented on R/extractDocumentation.R
> +     if (!is.null(extraPage)) {
This part must not happen here. `extract_block` has the purpose to extract information from a code block and to return it. The creation of the markdown files happens somewhere else!

2023-11-13 16:21 UTC, fbenke-pik commented
Had a look at the code, and this won't work as it is. Jan, feel free to ignore this for now.

2023-11-13 16:34 UTC, fbenke-pik commented
Closing in favour of #22

2023-11-13 16:34 UTC, closed without merging