A couple of fixes.
pik-piam/goxygen pull request #4
Opened 2020-06-22 10:38 UTC by dklein-pik

Tests should succeed now.

2020-06-22 11:13 UTC, tscheypidi requested changes
can you add a yml header to the vignette including a title as this title will then later show in the overview of vignetttes. For comparison have a look at the header of the madrat vignette:
```
---
title: "Data preparation with MADRaT"
author: "Jan Philipp Dietrich"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Data preparation with MADRaT}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---
```

2020-06-22 15:37 UTC, dklein-pik commented
War schon drin, oder nicht?

2020-06-22 20:49 UTC, tscheypidi commented
> War schon drin, oder nicht?

Oh sorry...you are correct. Somehow did not see it in my first review. 

But could you give it a bit more telling title. Especially, as this title is also copied to the README.md

2020-06-23 10:03 UTC, tscheypidi approved these changes

2020-06-23 10:03 UTC, merged